### ISSUE TITLE
Uncaught TypeError: this.checkForNotifications is not a function

### ISSUE THREAD

**Issue by jonkemp** [zephraph/atom-github-notifications#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Mac OS X 10.10.5
**Thrown From**: [github-notifications](https://github.com/zephraph/atom-github-notifications) package, v0.1.0
### Stack Trace

Uncaught TypeError: this.checkForNotifications is not a function

```
At /Users/160596/.atom/packages/github-notifications/lib/github-notifications.coffee:79

TypeError: this.checkForNotifications is not a function
  at module.exports.GithubNotifications.checkForNotifications (/Users/160596/.atom/packages/github-notifications/lib/github-notifications.coffee:79:10)

```
### Commands

```
     -4:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.3.0 core:paste (atom-text-editor#github-notifications.notificationAuthToken.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "github-notifications": {
    "notificationAuthToken": "<scrubbed>"
  }
}
```
### Installed Packages

``` coffee
# User
editorconfig, v1.2.0
github-notifications, v0.1.0
jshint, v1.8.0
linter, v1.6.0
linter-jscs, v3.0.0
linter-less, v2.1.0
monokai, v0.18.0

# Dev
No dev packages
```

^^^ Atom generated bug report

**Comment by averrin** [comment]
+1

**Comment by just-be-dev** [comment]
This _should_ be resolved (sort of) in 0.1.1. I put a check in place so that when `checkForNotifications` is called in the place where it failed it will check if it exists before actually performing the call. This is a bandaid... I haven't occurred this issue, but if it happens now I suspect all that will happen is that the notifications icon won't appear until after the first poll.

**Comment by beregond** [comment]
Unfortunatelly I have similar problem.

Notifications don't work (nothing is shown) and this is what I get after explicitely tell to refresh notifications:

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 15.04
**Thrown From**: [github-notifications](https://github.com/zephraph/atom-github-notifications) package, v0.1.1

### Stack Trace

Uncaught TypeError: this.checkForNotifications is not a function

```
At /home/szczepan/.atom/packages/github-notifications/lib/github-notifications.coffee:49

TypeError: this.checkForNotifications is not a function
  at atom-workspace.subscriptions.add.atom.commands.add.github-notifications:refresh (/home/szczepan/.atom/packages/github-notifications/lib/github-notifications.coffee:49:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:26.8.0 command-palette:toggle (div.panels-item)
     -0:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 sync-settings:backup (div.panels-item)
     -0:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.9.0 command-palette:toggle (div.package-detail.panels-item)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 github-notifications:refresh (div.package-detail.panels-item)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      "*.pyc",
      "__pycache__"
    ],
    "disabledPackages": [
      "minimap-git-diff"
    ]
  },
  "github-notifications": {
    "notificationAuthToken": "<meh>"
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-python, v0.10.0
clipboard-plus, v0.5.1
django-templates, v0.5.0
editor-settings, v1.0.4
file-icons, v1.6.11
git-log, v0.4.1
github-notifications, v0.1.1
highlight-selected, v0.10.1
language-docker, v1.1.3
language-dotenv, v1.0.0
last-cursor-position, v0.9.0
linter, v1.10.0
linter-flake8, v1.9.1
linter-pep8, v1.0.1
linter-pylama, v0.2.0
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
nuclide-hg-repository, v0.0.32
rst-preview-pandoc, v0.1.11
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
tree-view-git-status, v0.2.2
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

**Comment by just-be-dev** [comment]
I'm in the middle of a rewrite, so hopefully this issue will be solved from that.

**Comment by beregond** [comment]
@zephraph ok, thanks for quick answer :+1:

**Comment by nonameolsson** [comment]
How's it going with te rewrite? I'm still having this problem.
